name: abc-gan
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - tensorboard
  - seaborn
  - scikit-image
  - scikit-learn
  - pip:
      - tensorflow==2.12.0
      - keras-tuner==1.3.5
      - tensorflow-datasets==4.4.0
      - kaggle
      - tensorflow-addons[tensorflow]
      - tf-keras-vis
