name: abc-gan
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - tensorflow-deps
  - pandas
  - seaborn
  - pip=21.1.2
  - scikit-learn
  - scipy
  - matplotlib
  - pillow
  - tqdm
  - h5py
  - typeguard
  - pip:
      - tensorflow-macos==2.12.0
      - tensorflow-datasets
      - kaggle
      - keras-tuner
      - lime
      - tf-explain
      - imutils